// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_HEADERS_H_
#define _BEHAVIAC_AGENT_HEADERS_H_

#include "behaviac_headers.h"

// THE FOLLOWING AGENT HEADER FILES IS GENERATED AUTOMATICALLY:
#include "GameObject.h"
#include "Projectile.h"
#include "Ship.h"
#include "WorldState.h"

#endif // _BEHAVIAC_AGENT_HEADERS_H_
